# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLogInTSTDirectRep():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_logInTSTDirectRep(self):
    self.driver.get("https://mingle-portal.inforcloudsuite.com/KINRO_TST?Identity=Mingle")
    self.driver.find_element(By.ID, "username").send_keys("sromanowski@lci1.com")
    self.driver.find_element(By.ID, "pass").send_keys("EnterpriseQuoting3!")
    self.driver.find_element(By.CSS_SELECTOR, ".ping-button").click()
    self.driver.switch_to.frame(4)
    self.driver.find_element(By.CSS_SELECTOR, ".AddDark > .v-caption").click()
  
